### ISSUE TITLE
Why make it a function

### ISSUE THREAD

**Issue by eorroe** [prettydiff/Array.prototype.last#1]
Why not do this instead:

```
Object.defineProperty(Array.prototype, 'last', {
  get() {
    return this[this.length - 1];
  }
});

var arr = [1,2,3];

console.log(arr.last); // 3
```

**Comment by prettydiff** [comment]
Agreed, that is better.  I will modify the proposal the proposal and close this issue only after the pull request reflects this change.

**Comment by eorroe** [comment]
Yea my bad I was kind of distracted while posting this, I then realized that I opened your repository from the reddit post, after I posted this I saw that they already mentioned this. But yea this has been discussed already but it doesn't matter if your the one who ends up making this happen then I give you credit. Also for `first` as well:

```
Object.defineProperties(Array.prototype, {
  first: {
    get() {
      return this[0];
    }
  },
  last: {
    get() {
      return this[this.length - 1];
    }
  }
});

var arr = [1,2,3];

console.log(arr.last, arr.first); // 3, 1
```

**Comment by prettydiff** [comment]
A `first` method is not so needed in my opinion.  For arrays that are not sparse the first index will always be index 0.  This is always known, which is the primary difference between a last method because the length of the array is not always known. I am not concerned with sparse arrays, because they do not compile efficient in JIT engines.

**Comment by eorroe** [comment]
Forgot to mention, yes to almost everybod who already codes in javascript it wouldn't bother us, now people coming from another language or even a beginner may ask why there isn't a first. So it kind of makes sense to have both.

**Comment by prettydiff** [comment]
Updated in both this repo and the pull request - https://github.com/tc39/ecma262/pull/36

**Comment by ljharb** [comment]
Personally I would prefer it as a method - making it a getter means it can not be shimmed in ES3 engines - also, I believe the performance using a getter will likely be much slower.

**Comment by eorroe** [comment]
Ok I disagree with the getter being much slower because the getter is a function which is only one function call, same as calling it as a function no difference. Now shimmed in ES3 that would have to be with babel transpiling the getter into a function, because `Array.prototype.last` would land in ES7 if it gets accepted meaning this would only be for modern browsers because only modern browsers support ES6, ES7, ES8 etc unless transpiled with babel. Even though babel transpiles to ES5 so idk

`[1,2,3].last` a function called once

`[1,2,3].last()` a function called once

So I see no difference

```
Array.prototype.last = function() {
    return this[this.length - 1];
}

for(var i = 0, arr = []; i < 1e6; i++) arr.push(i);

console.time('function');
console.log(arr.last());
console.timeEnd('function');

Object.defineProperty(Array.prototype, 'last', {
    get() {
        return this[this.length - 1];
    }
});
for(var i = 0, arr = []; i < 1e6; i++) arr.push(i);

console.time('getter');
console.log(arr.last);
console.timeEnd('getter');
```

**Matter of fact `getter` seems to be faster on my side tested in chrome 42 stable**

**Comment by eorroe** [comment]
Never mind it comes out different `ms` every time. But again one function call so same thing

**Comment by prettydiff** [comment]
@ljharb I just created a perf to test this: http://jsperf.com/array-prototype-last/3

It would be wise to note that speed tests only test implementation of non-standard functionality in the present. An optimized standard will likely perform differently.

**Comment by eorroe** [comment]
Nice! but it keeps changing for me which is fastest, idk but speed is.

**Comment by ljharb** [comment]
I can't see how a getter would be any faster than a prototype method when native - the getter function could still be user-overridden, and so would prevent the same inlining, or afford the same optimizations as a prototype method. Using getters is still generally slower than functions, and the only advantage I see to a getter is to avoid having to type `()`, at the cost of not being able to polyfill it in ES3 browsers, which includes IE 8 - a still very widely-supported browser.

It is absolutely not a reasonable assumption that everyone is using a transpiler, or will use one. Shims are still used heavily and widely as the sole means of using newer language API surfaces in older browsers, even though solutions like Babel are gaining prominence.

**Comment by eorroe** [comment]
Well I said `babel`, because `babel` is a transpiler for `ES6+` so like I said `Array.prototype.last` would land in `ES7` and I meant a `getter` on the `prototype`, and if you call `Object.defineProperty` again you'll get an error saying `last` can't be redefined. And you're right:

> It is absolutely not a reasonable assumption that everyone is using a transpiler, or will use one.

I myself don't use it, however Ik about it. Just like `Array.prototype.includes` is part of `ES7` I'm sure `.last` will be as well. And not a part of `ES3` unless transpiled just like `.includes()` is transpiled.

**Comment by ljharb** [comment]
https://www.npmjs.com/package/es7-shim mostly works in ES3 browsers without any need for a transpiler, and `Array#last` would be included as well with the same goal. Transpilation has never been a requirement for new API methods to be injected into older browsers. See http://npmjs.com/es5-shim and http://npmjs.com/es6-shim as well.

**Comment by eorroe** [comment]
I've heard of `NPM` I'm not sure about that, so I may be completely wrong I apologize. IDK then for that, but for modern browsers to natively implement that I'm sure `.last` would land in `ES7` which at least chrome has barely touched on, only `Object.observe`

Well to put it in a phrase 

> "IDK then, I'm not sure about shimming"

But I'm still confused why you would think a `getter` is slower? Now so that it works for `ES3` browsers I understand, and the fact that an array is always going to return the last item, I think most will prefer as a `getter` since it's always returning the same thing, a `function` yea it may return the same thing depends but Idk IMO it seems like a getter would be better. IDK that will all depend on the web community's vote.

I mean looking at the future, us coding in `ES7` are most likely targeting modern browsers, yea it's nice for it to work in outdated browsers as well and some are targeting those as well, but I could be totally wrong. Yea then that would mean anybody targeting ES3 browsers would have to do extra work, but is that necessarily a bad thing when it comes to the language not the browser, I'm sure we would like everyone to move on from those browsers, but not have our api's having to support for them? That's what polyfills and shims and transpilers are for.

**Comment by ljharb** [comment]
Most JS engines haven't optimized getters and setters the way they've optimized prototype property lookup. Getters can be overridden by users just like prototype methods, so they're in no way more likely to "always return the same thing" - in both cases, the engine has to dynamically look up on the prototype chain in order to invoke the appropriate function.

**Comment by eorroe** [comment]
Yes with the `configurable` being `true`, so what if `configurable` is `false`? 

Wait you said:

> the way they've optimized prototype property lookup

Does that include methods?

**Comment by ljharb** [comment]
The committee tends to be **very strongly** against making things configurable false - pretty sure that just won't fly, I can tell you that now.

Yes, methods are just functions looked up via property, so it'd be just as fast as any other value.

**Comment by eorroe** [comment]
No I understand but sometimes people would use the word `methods` inclusive or exclusively even though they are but can be talked about exclusively.

BTW I think you misunderstood what I meant by returning the same thing:

Take for example:

```
var a = [0,1,2,3];
a.length // returns 4
a.length = 0; // empties array

// what if this worked with last:
a.last // returns 3
a.last = 4; // changes the 3 to a 4
a // [0,1,2,4];
```

That'd be part of the setter

So last may return something different obviously when something is pushed or poped or etc

Remember you can't do this if it's a function:

```
a.last() = 5;
```

`.last()` may also return something different but (wow I really don't know how to explain my feel, because it's something but I can't seem to explain it)

I don't know it's just kind of reminding me of java a bit, like the only one that I can think of is:

`document.body.hasChildNodes()` which makes sense to me as a function

It's like reading it "go check if it has childNodes" and `last` is like what's the last element in the array, but if it's a function "go get get me the last element in the array`

I don't know we'll just have to wait and see.

**Comment by ljharb** [comment]
The setter case you describe is definitely a use case that the function doesn't afford you. However, mutating arrays imo is an antipattern, so I still prefer the read-only function behavior :-)

**Comment by prettydiff** [comment]
@ljharb Getters and setters are awful and not well optimized, but this is an implementation detail. The awfulness goes away with any optimized native code implementation. In the end all that matters is that there is either a property or method with an agreed name that represents an agree conclusion.

I like the property `last` more than a method `last()` because there is no action to be performed. When I look at array methods they do something to the array. The `length` property does nothing to the array and is read only so therefore it is a property and not a method. The proposed item will also do nothing and be read only.

**Comment by ljharb** [comment]
`var arr = [1]; arr.length = 0;` The `length` property absolutely does something to the array, and is in no way read only - people will expect a `last` property to do that also.

**Comment by eorroe** [comment]
@prettydiff @ljharb is write it **empties**  the `array` when you set it to `0`, but @ljharb are you saying `last` should do the same as I mentioned about with the `setter` `arr.last = 2`? Because `arr.last(2)` it doesn't look bad but no just really bad if someone was just learning about it, `last()` without arguments returns the last but passing an argument sets it. (I'm not saying that's what you implied, ik you didn't just mentioning it)

**Comment by ljharb** [comment]
Yes. If it is a property, it must function both as a getter and a setter, otherwise it will be surprising. Whereas `.last()` solely returning the last item would not be.

The pattern you're describing of `.foo()` for read, and `.foo(x)` for write, is prevalent in jQuery, but I'm not aware of anything in ECMAScript that has that pattern - I'd not expect a (controversial) pattern like that to be introduced to the spec.

**Comment by eorroe** [comment]
Agreed

**Comment by dcrockwell** [comment]
+1 to .last vs .last()
